name: Cypress Test

on: 
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci
          npm install cypress --save-dev

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev  # Comando real de tu app
          wait-on: "http://localhost:3000"
          browser: chrome
          record: true  # Opcional para Cypress Dashboard
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
