name: Cypress Test

on: [push]
 
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Versión actualizada

      - name: Install dependencies
        run: npm ci  # Mejor que 'npm install' para CI

      - name: Run Cypress
        uses: cypress-io/github-action@v6  # Versión actualizada
        with:
          start: npm start  # Comando para iniciar tu app
          wait-on: "http://localhost:3000"  # ¡Añade esto! Cambia el puerto si es necesario
          browser: chrome  # Recomendado explícitamente
