on: [push, workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm start       # Usa el script que definimos
          wait-on: "http://localhost:3000"
          browser: chrome
