name: Cypress Test

on: [push, workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  
      # Opción 2 (alternativa): Usa npm install
      - name: Install dependencies
        run: npm install

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: "http://localhost:3000"
          browser: chrome
