name: Cypress Test

on: [push, workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Asegura que se descargue todo el historial

      - name: Verify files
        run: |
          ls -la  # Lista archivos para debug
          if [ ! -f package.json ]; then
            echo "❌ Error: package.json no encontrado"
            exit 1
          fi

      - name: Install dependencies
        run: npm install

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: "http://localhost:3000"
          browser: chrome
