name: Cypress Test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Cypress.io
      uses: cypress-io/github-action@v6.5.0
      with:
       strat: npx cypress open

    
